name: Fetch and Delete Account

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions tab

jobs:
  fetch_and_delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Fetch and delete account
        run: node fetch-and-delete.js

      - name: Commit changes (if any)
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Fetched and removed account from accounts.json'
